version: "3"
services:
  python_app:
    build: ./python-app
    container_name: python-app
    restart: always
    network_mode: host
    ports:
      - 5000:5000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always
    network_mode: host


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    depends_on:
      - prometheus
    restart: always
    network_mode: host

